export const API_URLS = {
  signup: "auth/register",
  login: "auth/login",
  refreshToken: "auth/refresh-token",
  logout: "auth/logout",
  forgotPassword: "auth/forgot-password",
  resetPassword: "auth/reset-password",
  getAllRoles: "roles/getAllRoles",
  getAllRolesPaginated: "roles",
  getAllRooms: "rooms",
  getAllUsers: "users",
  assignRoles: "users/assignRoles/",
  removeRoles: "users/removeRoles/",
  removeAllRoles: "users/removeAllRoles/",
};
